title: Muxin Wei

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://muxin-wei.github.io/"
footer_text: "Muxin Wei's Homepage"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/muxin-wei"
 - name: "Email"
   link: "mailto:muxin.wei@foxmail.com"
