title: Muxin Wei's Homepage

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/muxin-wei"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/muxin-wei"
 - name: "Email"
   link: "mailto:muxinwei@foxmail.com"
