title: Muxin Wei
url: "https://muxin-wei.github.io/"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://muxin-wei.github.io/"
footer_text: "Muxin Wei's home page"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/muxin-wei"
 - name: "Demo"
   link: "/demo"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/muxin-wei-90a335332/"
 - name: "Email"
   link: "mailto:muxin.wei@foxmail.com"
 - name: "Resume"
   link: "./CV.pdf"